---
  temp_folder: /tmp
  go_version: go1.7.linux-amd64.tar.gz
  go_url: https://storage.googleapis.com/golang/{{ go_version }}
  go_hash: sha256:702ad90f705365227e902b42d91dd1a40e48ca7f67a2f4b2fd052aaa4295cd95
  go_project_dir: goprojects
  go_home: "{{ ansible_env.HOME }}"
  gogs_home: "/home/git"
  gogs_project_directory: "git.varaunited.net"
  gogs_repo: github.com/gogits/gogs
